cache: bundler
language: ruby
sudo: false

addons:
    apt:
        packages:
            - aspell
            - aspell-en
            - aspell-fr

script: ./bin/spellcheck.sh

before_script:
  - chmod +x ./bin/build.sh
